#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/cpp for more hints
#
# lint http://lint.travis-ci.org/WPN-XM/server-control-panel
#
language: cpp

branches:
  only:
    - master

cache:
  apt: true

matrix:
  fast_finish: true
  include:
    # cross-compile using mingw
    - env: PLATFORM="mingw32" ARCH="x86_64" BITSIZE=64 HOST="x86_64"
    - env: PLATFORM="mingw32" ARCH="x86" BITSIZE=32 HOST="i686"
  allow_failures:
      - BITSIZE: 32

install:
  # < Mingw Repo
  - sudo add-apt-repository --yes ppa:tobydox/mingw-x-precise
  - sudo apt-get update -qq
  # < NUM_CPU (for make jobs)
  - export NUM_CPU="`grep processor /proc/cpuinfo | wc -l`"; echo $NUM_CPU
  - uname -m
  # Install
  - sudo apt-get install -y zip cloog-isl mingw32
  - if [ $BITSIZE == 32 ]; then sudo apt-get install -y mingw32-x-binutils mingw32-x-gcc mingw32-x-runtime mingw32-x-qt5base; fi
  - if [ $BITSIZE == 64 ]; then sudo apt-get install -y mingw64-x-binutils mingw64-x-gcc mingw64-x-runtime mingw64-x-qt5base; fi
  - export MINGW=/opt/mingw$BITSIZE
  - export PATH=$MINGW/bin:$PATH
  - export CC=$HOST-w64-mingw32-gcc
  - export CXX=$HOST-w64-mingw32-g++

script:
  - which qmake
  - qmake -query
  - qmake -v
  - qmake wpnxm-servercontrolpanel.pro CONFIG+=release QMAKE_CC=$CC QMAKE_CXX=$CXX
  - gcc -v
  - gcc -dumpmachine
  # insert version
  - ant main
  - cat /home/travis/build/WPN-XM/server-control-panel/src/version.h
  # build
  - make -j$NUM_CPU VERBOSE=1

after_success:
  - if [ -f /home/travis/build/WPN-XM/server-control-panel/release/wpn-xm.exe ]; then
      zip -r release.zip /home/travis/build/WPN-XM/server-control-panel/release -i '*.exe' '*.dll'
    else
      echo "[wpn-xm.exe] File not found."
    fi
  # send build artifact home
  # publish only, if not a "pull request" and on "master" branch
  # - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && ]]; then deploy; fi
  # fetch Qt Deployment package (dlls)
  # ...
  # test executable with wine
  #- sudo ls -alh /home/travis/build/WPN-XM/server-control-panel/release/*
  #- sudo apt-get install -y wine
  #- wineconsole --backend=curses /home/travis/build/WPN-XM/server-control-panel/release/wpn-xm.exe --help

#deploy:
#  provider: releases
#  api-key: "GITHUB OAUTH TOKEN"
#  file: "FILE TO UPLOAD"
#  skip_cleanup: true
#  on:
#    condition:
#    tags: true
#    all_branches: true

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true