#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/cpp for more hints
#
language: cpp

cache:
  apt: true

matrix:
  fast_finish: true
  include:
    # cross-compile using mingw
    - compiler: ": w64"
      env: PLATFORM="mingw32" ARCH="x86_64" BITSIZE=64 HOST="x86_64"
    - compiler: ": w32"
      env: PLATFORM="mingw32" ARCH="x86" BITSIZE=32 HOST="i686"

install:
  # < 7zip
  - sudo apt-get install p7zip-full
  # < Qt
  - if [ $BITSIZE == 32 ]; then sudo wget -O qt.zip http://sourceforge.net/projects/mingwbuilds/files/external-binary-packages/Qt-Builds/x32-Qt-5.2.1%2BQtCreator-3.0.1-%28gcc-4.8.2-dwarf%29.7z/download; fi
  - if [ $BITSIZE == 64 ]; then sudo wget -O qt.zip http://sourceforge.net/projects/mingwbuilds/files/external-binary-packages/Qt-Builds/x64-Qt-5.2.1%2BQtCreator-3.0.1-%28gcc-4.8.2-seh%29.7z/download; fi
  # unzip Qt to /opt/qt5 and set path variable
  - 7z x qt.zip -o/opt/qt5 -y
  - uname -m
  - export QTDIR=/opt/qt5
  - export PATH=$QTDIR/bin:$PATH
  - export LD_LIBRARY_PATH=$QTDIR/lib/:$QTDIR/lib/`uname -m`-linux-gnu:$LD_LIBRARY_PATH
  # < MinGW
  - sudo add-apt-repository --yes ppa:tobydox/mingw-x-precise
  - sudo apt-get update -qq
  - sudo apt-get install -y cloog-isl mingw32
  - if [ $BITSIZE == 32 ]; then sudo apt-get install -y mingw32-x-binutils mingw32-x-gcc mingw32-x-runtime; fi
  - if [ $BITSIZE == 64 ]; then sudo apt-get install -y mingw64-x-binutils mingw64-x-gcc mingw64-x-runtime; fi
  - export MINGW=/opt/mingw$BITSIZE
  - export PATH=$MINGW/bin:$PATH
  - export CC=$HOST-w64-mingw32-gcc
  - export CXX=$HOST-w64-mingw32-g++

script:
  - qmake -v
  - qmake wpnxm-servercontrolpanel.pro CONFIG+=release QMAKE_CC=$CC QMAKE_CXX=$CXX
  - gcc -v
  - gcc -dumpmachine
  - export CMAKE_OPTS="-DUSE_WERROR=ON"
  - make -j2 VERBOSE=1

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true