#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/cpp for more hints
#
language: cpp

cache:
  apt: true

matrix:
  fast_finish: true
  include:
    # cross-compile using mingw
    - compiler: ": w64"
      env: HOST=x86_64 PLATFORM="mingw32" ARCH="x86_64" BITSIZE=64
    - compiler: ": w32"
      env: HOST=i686 PLATFORM="mingw32" ARCH="x86" BITSIZE=32

install:
  - sudo add-apt-repository "deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe multiverse" -y # < Update to Ubuntu Trusty
  - sudo add-apt-repository --yes ppa:beineri/opt-qt54                   # < Qt
  - sudo add-apt-repository --yes ppa:tobydox/mingw-x-trusty             # < MinGW
  - sudo sed -i 's/trusty/precise/g' /etc/apt/sources.list.d/tobydox-mingw-trusty.list  # <  Change the "trusty" release tags to "precise"
  - sudo apt-get update -qq
  - sudo apt-get install qt54base qt54imageformats qt54tools -y -qq
  - uname -m
  - export QTDIR=/opt/qt54
  - export PATH=$QTDIR/bin:$PATH
  - export LD_LIBRARY_PATH=$QTDIR/lib/:$QTDIR/lib/`uname -m`-linux-gnu:$LD_LIBRARY_PATH
  - sudo apt-get install -y cloog-isl mingw32
  - if [ $BITSIZE == 32 ]; then sudo apt-get install -y mingw-x-qt5base mingw32-x-pkgconfig mingw32-x-binutils mingw32-x-gcc mingw32-x-runtime; fi
  - if [ $BITSIZE == 64 ]; then sudo apt-get install -y mingw-x-qt5base mingw64-x-pkgconfig mingw64-x-binutils mingw64-x-gcc mingw64-x-runtime; fi
  - export MINGW=/opt/mingw$BITSIZE
  - export PATH=$MINGW/bin:$PATH
  - export CC=$HOST-w64-mingw32-gcc
  - export CXX=$HOST-w64-mingw32-g++

script:
  - qmake -v
  - qmake wpnxm-servercontrolpanel.pro CONFIG+=release QMAKE_CC=$CC QMAKE_CXX=$CXX
  - gcc -v
  - gcc -dumpmachine
  - export CMAKE_OPTS="-DUSE_WERROR=ON"
  - make -j2 VERBOSE=1

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true