#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/cpp for more hints
#
language: cpp

cache:
  apt: true

matrix:
  fast_finish: true
  include:
    # cross-compile using mingw
    - compiler: "- w64"
      env: HOST=x86_64-w64-mingw32 PLATFORM="mingw32" ARCH="x86_64"
    - compiler: "- w32"
      env: HOST=i686-w64-mingw32 PLATFORM="mingw32" ARCH="x86"

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt54                     # < Qt
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test              # < GCC
  - sudo add-apt-repository --yes ppa:tobydox/mingw-x-precise              # < MinGW
  - sudo apt-get update -qq
  - sudo apt-get install qt54base qt54imageformats qt54tools -y -qq
  - uname -m
  - export QTDIR=/opt/qt54
  - export PATH=$QTDIR/bin:$PATH
  - export LD_LIBRARY_PATH=$QTDIR/lib/:$QTDIR/lib/`uname -m`-linux-gnu:$LD_LIBRARY_PATH
  #- sudo apt-get install gcc-4.9 g++-4.9 gdb -y -qq
  #- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - sudo apt-get install mingw32-x-binutils mingw32-x-gcc mingw32-x-runtime -y -qq
  - export CC=$HOST-gcc
  - export CXX=$HOST-g++

#install:
  #- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
  #- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi

script:
  - qmake -v
  - qmake wpnxm-servercontrolpanel.pro CONFIG+=release QMAKE_CC=$CC QMAKE_CXX=$CXX
  - gcc -v
  - g++ -v
  - make -j2 VERBOSE=1

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true